apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a4yzu6lc8-python 
  janus-idp.io/tekton: a4yzu6lc8-python
  backstage.io/kubernetes-id: a4yzu6lc8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a4yzu6lc8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  