apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: a4yzu6lc8-python-gitops
  description: This is GitOps manifest for a4yzu6lc8-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=a4yzu6lc8-python
    backstage.io/kubernetes-id: a4yzu6lc8-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: a4yzu6lc8-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:a4yzu6lc8-python
