apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: a4yzu6lc8-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7d7fd3fa17.h2hf.p3.openshiftapps.com/rhtap/rhtap-qe:300a72b446efceb9c3a0a1eae0ba3946b35559e4@sha256:a424b7c818bdeeb1c573328b8caccff1cd12388229b20da60ff826aa86a00af7
          name: container-image
